name: Jekyll Deploy

on:
  push:
    branches:
      - main
      - feature/gh-pages-jekyll
    paths-ignore:
      - "Gemfile"
      - "README.md"
      - "LICENSE.md"

# Build site using jekyll
jobs:
  jekyll:
    runs-on: ubuntu-latest
    steps:
      # checkout code
      - uses: actions/checkout@v2
      # Use ruby/setup-ruby to shorten build times
      # https://github.com/ruby/setup-ruby
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3.0 # Not needed with a .ruby-version file
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
      # Install Node as this is needed for PostCSS
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: "20"
      # Install PostCSS plugins (from your package.json)
      - run: npm install
      # Install bundler
      - run: gem install bundler
      # Install needed gems
      - run: bundle install
      # Build the site
      - run: bundle exec jekyll build --verbose
      # use actions-gh-pages to deploy
      # https://github.com/peaceiris/actions-gh-pages
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          # GITHUB_TOKEN secret is set up automatically
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
