name: jekyll-build-and-serve

on:
  push:
    branches:
      - main

jobs:
  github-pages:
    runs-on: ubuntu-latest
    steps:
      # Clones the directory
      - uses: actions/checkout@v2
      # Downloads and sets up ruby.
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3.0
          bundler-cache: true
      # Sets up nodejs
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: "lts/iron"
      # Run npm install to get postcss and tailwindcss
      - run: npm install
      # Run the jekyll build.
      - name: Build site
        uses: limjh16/jekyll-action-ts@v2
        with:
          enable_cache: true
      # Deploy the generated site.
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
